### ISSUE TITLE
Lil Roadmap 🥤

### ISSUE THREAD

**Issue by git2bezbar** [git2bezbar/game-of-life#3]
Toutes les pages sont disponibles [sur Figma](https://www.figma.com/design/gvdH6bzlWpVtAkk4PYkS2V/Design-stuff-%E2%9C%A8?node-id=76-3581&t=IVzuba8y8jYsWSFv-0)
### Général
- [x] Ajouter le header
- [x] Ajouter le footer
### Game of Life
- [x] Game of Life | Accueil 🏠
- [x] Game of Life | Règles 📄
- [ ] Game of Life | Simulateur 🕹️ (⏳ @LeonardPaillet)
- [x] Game of Life | Wiki 🌐
- [x] Game of Life | Wiki | Type 🌐
- [x] Game of Life | Wiki | Single 🌐
### Kreator
- [x] Kreator | Connexion
- [x] Kreator | Fiche 📄
- [x] Kreator | Fiche 📄 | Ajout
- [x] Kreator | Fiche 📄 | Modification
- [x] Kreator | Fiche 📄 | Suppression
- [x] Kreator | Type ✨
- [x] Kreator | Type ✨ | Ajout
- [x] Kreator | Type ✨ | Modification
- [x] Kreator | Type ✨ | Suppression
### Game of Life
- [x] Game of Life | Simulateur 🕹️
- [x] Ajouter toutes les méthodes de l'API dans un dossier pour les utiliser plus facilement
### Kreator
- [x] Kreator | Connexion
- [x] Kreator | Fiche 📄 | Ajout (⏳ @git2bezbar)
- [x] Kreator | Fiche 📄 | Modification (⏳ @git2bezbar)
- [x] Kreator | Fiche 📄 | Suppression (⏳ @git2bezbar)
- [x] Kreator | Type ✨ | Ajout
- [x] Kreator | Type ✨ | Modification
- [x] Kreator | Type ✨ | Suppression
